name: Secrets and Variables Demo

on: [push]

jobs:
  test-secrets-and-vars:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Print Environment Variable
        run: echo "The environment is ${{ vars.MY_ENVIRONMENT_VARIABLE }}"

      - name: Access Secret (Masked in Logs)
        run: echo "The API Key is ${{ secrets.MY_SECRET_API_KEY }}"